apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.esStatefulSetName }}
spec:
  selector:
    matchLabels:
      app: elasticsearch-statefulset
  serviceName: elasticsearch-service
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: elasticsearch-statefulset
    spec:
      volumes:
        - name: elasticsearch-configmap-volume
          configMap:
            name: elasticsearch-configmap
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        ports:
        - containerPort: 9200
          name: web
        volumeMounts:
          - name: elasticsearch-configmap-volume
            mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
            subPath: elasticsearch.yml
          # - name: elasticsearch-data
          #   mountPath: /usr/share/elasticsearch/data
        env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1500m"
            memory: "3Gi"
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes: 
          - ReadWriteOnce
        storageClassName: elasticsearch-storage-class
        resources:
          requests:
            storage: 10Gi
